GET http://localhost:5252/games

###
GET http://localhost:5252/games/5

###
POST http://localhost:5252/games
Content-Type: application/json

{
  "title": "Test Game",
  "genreId": 4,
  "price": 45.99,
  "releaseDate": "2020-12-10"
}

###
PUT http://localhost:5252/games/4
Content-Type: application/json


{
  "title": "Mario Kart 8 Deluxe Updated",
  "genreId": 4,
  "price": 45.99,
  "releaseDate": "2020-12-10"
}

###
DELETE http://localhost:5252/games/5